@startuml

hide footbox

title GetNumOfROMCodeFound sequence

participant "OneWireDriver" as ModuleOneWireDriver<<M,Green>>[[../Class/OneWireDriver.svg]]



-> ModuleOneWireDriver : GetNumOfROMCodeFound()
  activate ModuleOneWireDriver

<-- ModuleOneWireDriver : numOfDeviceFound
  deactivate ModuleOneWireDriver

@enduml
